#ifndef ITEM
#define ITEM(EnumName, ItemType, ItemName, ItemDesc) ;
#endif // !ITEM

// 1 - Weapon Upgradins, 2 - Rare Artifacts, 3 - Quest Item's, 4 - Useds Items, 5 - Crafted Item
// Sufix S - SettingsItem

ITEM(MONEYBAG, 4, "Money Bag", "- Random get 5-20000 silvers")
ITEM(PIGPORNO, 3, "Quest Pig Meat", "- Need for quest")
ITEM(KWAHGANDON, 3, "Quest Kwah Head", "- Need for quest")
ITEM(HOOKDAMAGE, 1, "Hook Damage", "- Weapon / Upgrading")
ITEM(IGUN, 1, "Gun", "- Weapon / Upgrading")
ITEM(ISHOTGUN, 1, "Shotgun", "- Weapon / Upgrading")
ITEM(IGRENADE, 1, "Grenade", "- Weapon / Upgrading")
ITEM(ILASER, 1, "Laser", "- Weapon / Upgrading")
ITEM(AMULETCLEEVER, 2, "Amulet Cleever", "This for got x2 money bag in level up")
ITEM(RINGNOSELFDMG, 2, "Ring Selfine", "This for don\"t get self damage")
ITEM(AHAPPY, 5, "Module Happy", "Emote module if all modules + bonus")
ITEM(AEVIL, 5, "Module Evil", "Emote module if all modules + bonus")
ITEM(ASUPRRISE, 5, "Module Surprise", "Emote module if all modules + bonus")
ITEM(ABLINK, 5, "Module Blink", "Emote module if all modules + bonus")
ITEM(APAIN, 5, "Module Pain", "Emote module if all modules + bonus")
ITEM(CLANTICKET, 3, "Ticket Create Clan", "Ticket for created clan")
ITEM(MODULEEMOTE, 2, "Module Emote", "Emote module if all modules + bonus")
ITEM(ALPHABOX, 4, "Alpha Box", "This bonus in alpha")
ITEM(SKILLUPBOX, 4, "SP Upgrade Box", "This bonus in alpha")
ITEM(LEATHER, 2, "Leather", "Craft Item")
ITEM(SNAPHPREGEN, 2, "Rare Draw HP Regen", "Rare | This drawing item")
ITEM(SNAPDAMAGE, 2, "Rare Draw Damage", "Rare | This drawing item")
ITEM(SNAPHANDLE, 2, "Rare Draw Handle", "Rare | This drawing item")
ITEM(SNAPAMMOREGEN, 2, "Rare Draw Ammo Regen", "Rare | This drawing item")
ITEM(RARERINGSLIME, 2, "Rare Ring Slime", "Rare | Not self damage and jump")
ITEM(RARESLIMEDIRT, 5, "Slime Dirt", "Item for craft")
ITEM(FORMULAFORRING, 5, "Formula Ring\"s", "Item for craft")
ITEM(EXGUN, 1, "Module Explode Gun", "- Weapon / Upgrading")
ITEM(EXSHOTGUN, 1, "Module Explode Shotgun", "- Weapon / Upgrading")
ITEM(EXLASER, 1, "Module Explode Laser", "- Weapon / Upgrading")
ITEM(WEAPONPRESSED, 1, "Weapon Pressed", "- All Weapon +5 ammo")
ITEM(HEADBOOMER, 5, "Body Boomer", "Item for craft")
ITEM(RINGBOOMER, 2, "Rare Ring Boomer", "Rare | Health +5% and item for craft")
ITEM(FORMULAEARRINGS, 5, "Formula Earring\"s", "Item for craft")
ITEM(FORMULAWEAPON, 5, "Formula Weapon\"s", "Item for craft")
ITEM(MODULESHOTGUNSLIME, 1, "Module Shotgun Slime", "- Weapon / Upgrading")
ITEM(EARRINGSKWAH, 1, "Rare Earrings Kwah", "Item added +1 jump mabe stack")
ITEM(FOOTKWAH, 5, "Foot Kwah", "Item for craft")
ITEM(BOOKMONEYMIN, 4, "Book Money x2 (10min)", "Book item\"s for added bonus")
ITEM(BOOKEXPMIN, 4, "Book Experince x2 (10min)", "Book item\"s for added bonus")
ITEM(RELRINGS, 2, "Jioc Dual Ring\"s", "Rare | Relation get -10")
ITEM(MODULEHOOKEXPLODE, 1, "Module Hook Explode", "- Module hook damage in explode")
ITEM(HAMMERAUTO, 1, "Auto Hammer", "- Auto Fire Hammer")
ITEM(GUNAUTO, 1, "Auto Gun", "- Auto Fire Gun")
ITEM(GHOSTGUN, 1, "Module Ghost Gun", "- Fire Ghost in Wall")
ITEM(GHOSTSHOTGUN, 1, "Module Ghost Shotgun", "- Fire Ghost in Wall")
ITEM(GHOSTGRENADE, 1, "Module Ghost Grenade", "- Fire Ghost in Wall")
ITEM(WHITETICKET, 2, "White Ticket", "- Need for Enter in White")
ITEM(FREEAZER, 1, "Rare Freeazer", "- %1 freeze for 1sec")
ITEM(RANDOMCRAFTITEM, 4, "Rand Box Craft", "- This box gived rand craft item")
ITEM(EVENTBOX, 4, "Event Box", "Event Box")
ITEM(RAREEVENTHAMMER, 1, "Rare Event Hammer", "- Snap & added +5 crit damage")
ITEM(GUNBOUNCE, 1, "Bounce Gun", "- Gun Ammo Bounce")
ITEM(HYBRIDSG, 1, "Hybrid SGUN", "- Hybrid Gun & Shotgun")
ITEM(GRENADEBOUNCE, 1, "Bounce Grenade", "- Grenade Ammo Bounce")
ITEM(MOONO2, 4, "Moon O2 / H2O", "- This need for area moon")
ITEM(LAMPHAMMER, 1, "Lamp Hammer", "- Content 18+")
ITEM(ZOMBIEBRAIN, 3, "Zombie Brain", "- Quest Item")
ITEM(ZOMBIEEYE, 5, "Zombie Eye", "- Craft Item")
ITEM(ZOMIBEBIGEYE, 5, "Big Zombie Eye", "- Craft Item")
ITEM(SKELETSBONE, 5, "Skelet Bone", "- Craft Item")
ITEM(SKELETSSBONE, 5, "Skelet Fortified Bone", "- Craft Item")
ITEM(SKELETSKULL, 3, "Skelet Skull", "- Quest Item")
ITEM(NIMFHEART, 5, "Nimf Hearth", "- Craft Item")
ITEM(NIMFEARS, 5, "Nimf Ears", "- Craft Item")
ITEM(NIMFBODY, 3, "Nimf Body", "- Quest Item")
ITEM(CLANBOXEXP, 4, "Clan Exp Bag", "- Added for clan 50000 exp")
ITEM(CUSTOMSKIN, 2, "Customized", "- This item for custom skin")
ITEM(RESETINGUPGRADE, 4, "Reseting Upgrades", "- This item used")
ITEM(RESETINGSKILL, 4, "Reseting Passive Skills", "- Reseting only pasive skill")
ITEM(ENDEXPLOSION, 1, "The end Explosion", "- This item added end Explosion")
ITEM(SCHAT, 10, "Output to the chat", "- Settings")
ITEM(SDROP, 10, "Pick Item", "- Settings")
ITEM(SKWALL, 10, "Skill Walls", "- Settings")
ITEM(SKHEAL, 10, "Skill Heal", "- Settings")
ITEM(VIPPACKAGE, 4, "VIP PACKAGE", "- Added more Bonuses")
ITEM(SANTIPVP, 10, "AntiPVP", "- Settings")
ITEM(SPECSNAPDRAW, 2, "VIP Draw Snap", "- VIP Item")
ITEM(X2MONEYEXPVIP, 12, "Title VIP", "- VIP x2 Money & Exp")
ITEM(SSWORD, 10, "Skill Sword", "- Settings")
ITEM(BOSSDIE, 12, "Title Boss?Die", "- Spawn HP +1000")
ITEM(PIGPIG, 12, "Title Pig Pig", "- Price -5%")
ITEM(BIGCRAFT, 12, "Title Big Craft", "- Not Bonuses")
ITEM(SHEALSUMMER, 10, "Skill Summer Healing", "- Event Skill Healing")
ITEM(ESUMMER, 5, "Sun Ray", "- Event Craft Item")
ITEM(TITLESUMMER, 12, "Title Summer", "- Title Special Events")
ITEM(POTATO, 4, "Potato", "- You got 50 exp")
ITEM(TOMATE, 4, "Tomate", "- You got 30 exp")
ITEM(CARROT, 4, "Carrot", "- You got 20 exp")
ITEM(JUMPIMPULS, 2, "Jump Impuls", "- Impuls jump")
ITEM(FARMLEVEL, 10, "Farming Exp", "- Farming Exp")
ITEM(FARMBOX, 4, "Farming Box", "- Random Reward")
ITEM(TITLEQUESTS, 12, "Title Questing System", "- 1500 HP | 500 Armor")
ITEM(WOOD, 5, "Wood", "- Craft Item")
ITEM(COOPERORE, 5, "Cooper Ore", "- Craft Item")
ITEM(COOPERPIX, 6, "Cooper Pickaxe", "- Miner Item")
ITEM(IRONORE, 5, "Iron Ore", "- Craft Item")
ITEM(IRONPIX, 6, "Iron Pickaxe", "- Miner Item")
ITEM(GOLDORE, 5, "Gold Ore", "- Craft Item")
ITEM(GOLDPIX, 6, "Gold Pickaxe", "- Miner Item")
ITEM(DIAMONDORE, 5, "Diamond Ore", "- Craft Item")
ITEM(DIAMONDPIX, 6, "Diamond Pickaxe", "- Miner Item")
ITEM(MINEREXP, 10, "Miner Exp", "- Miner Exp")
ITEM(BIGWOOD, 5, "Big Wood", "- Craft Item")
ITEM(DRAGONORE, 5, "Dragon Ore", "- Craft Item")
ITEM(EVENTCUSTOMSOUL, 3, "Particle Soul", "- Event Back to school")
ITEM(MATERIAL, 6, "Material", "- Work Item")
ITEM(LOADEREXP, 10, "Loader Exp", "- Loader Exp")
ITEM(PIZDAMET, 1, "Pizdamet", "- 50% -1 mana")
ITEM(LEATHERBODY, 15, "Leather body", "(Armor +100, Health +100)")
ITEM(LEATHERFEET, 16, "Leather feet", "- Health +50 Armor +50")
ITEM(STCLASIC, 17, "Stabilized Clasic", "- Damaage +1")
ITEM(COOPERBODY, 15, "Cooper body", "- Health Armor +150")
ITEM(COOPERFEET, 16, "Cooper feet", "- Health Armor +100")
ITEM(IRONBODY, 15, "Iron body", "- Health Armor +200")
ITEM(IRONFEET, 16, "Iron feet", "- Health Armor +150")
ITEM(GOLDBODY, 15, "Gold body", "- Health Armor +250")
ITEM(GOLDFEET, 16, "Gold feet", "- Health Armor +150")
ITEM(DIAMONDBODY, 15, "Diamond body", "- Health Armor +300")
ITEM(DIAMONDFEET, 16, "Diamond feet", "- Health Armor +250")
ITEM(DRAGONBODY, 15, "Dragon body", "- Health Armor +500")
ITEM(DRAGONFEET, 16, "Dragon feet", "- Health Armor +400")
ITEM(TITLEENCHANT, 10, "Title Enchanter", "- Health Armor +1000")
ITEM(BOSSBOX, 4, "BOSS SLIME BOX", "- Drops from boss Slime")
ITEM(SLIMESPHERE, 2, "SLIME SPHERE", "- Gives 10% hp and 5 % armor")
ITEM(SLIMENECKLACKE, 2, "SLIME NECKLACKE", "- Gives 10% hp")
ITEM(PRESSEDPIECE, 5, "Pressed piece", "- Need for craft ammo+5")
ITEM(BOSSBOX2, 4, "BOSS VAMPIRE BOX", "- Drops from boss Vampire")
ITEM(VAMPIREFANG, 2, "Vampire Fang", "- Gives lifesteal")
ITEM(BOSSBOX3, 4, "DARK KING BOX", "-Drops from boss Dark King")
ITEM(PIG_XP, 10, "PIG XP", "-Count Pig kills")
ITEM(KWAH_XP, 10, "KWAH XP", "-Count Kwah kills")
ITEM(BOOM_XP, 10, "BOOM XP", "-Count Boomer kills")
ITEM(PIGKILLER_1, 10, "PIGKILLER_1", "-Achieve")
ITEM(PIGKILLER_2, 10, "PIGKILLER_2", "-Achieve")
ITEM(PIGKILLER_3, 10, "PIGKILLER_3", "-Achieve")
ITEM(PIGKILLER_4, 10, "PIGKILLER_4", "-Achieve")
ITEM(PIGKILLER_5, 10, "PIGKILLER_5", "-Achieve")
ITEM(KWAHKILLER_1, 10, "KWAHKILLER_1", "-Achieve")
ITEM(KWAHKILLER_2, 10, "KWAHKILLER_2", "-Achieve")
ITEM(KWAHKILLER_3, 10, "KWAHKILLER_3", "-Achieve")
ITEM(KWAHKILLER_4, 10, "KWAHKILLER_4", "-Achieve")
ITEM(KWAHKILLER_5, 10, "KWAHKILLER_5", "-Achieve")
ITEM(BOOMKILLER_1, 10, "BOOMKILLER_1", "-Achieve")
ITEM(BOOMKILLER_2, 10, "BOOMKILLER_2", "-Achieve")
ITEM(BOOMKILLER_3, 10, "BOOMKILLER_3", "-Achieve")
ITEM(BOOMKILLER_4, 10, "BOOMKILLER_4", "-Achieve")
ITEM(BOOMKILLER_5, 10, "BOOMKILLER_5", "-Achieve")
ITEM(CRAFTMASTER_1, 10, "CRAFTMASTER_1", "-Achieve")
ITEM(CRAFTMASTER_2, 10, "CRAFTMASTER_2", "-Achieve")
ITEM(CRAFTMASTER_3, 10, "CRAFTMASTER_3", "-Achieve")
ITEM(CRAFTMASTER_4, 10, "CRAFTMASTER_4", "-Achieve")
ITEM(CRAFTMASTER_5, 10, "CRAFTMASTER_5", "-Achieve")
ITEM(CRAFTMASTER_6, 10, "CRAFTMASTER_6", "-Achieve")
ITEM(CRAFTMASTER_7, 10, "CRAFTMASTER_7", "-Achieve")
ITEM(MITHRIL_BODY, 15, "Mithril Chestplate", "- Health Armor +700")
ITEM(MITHRIL_FEET, 16, "Mithril Boots", "- Health Armor +600")
ITEM(MITHRILORE, 5, "Mithril Ore", "- Craft Item")
ITEM(ORIHALCIUM_BODY, 15, "Orihalcum Chestplate", "- Health Armor +1000")
ITEM(ORIHALCIUM_FEET, 16, "Orihalcum Boots", "- Health Armor +900")
ITEM(ORIHALCIUMORE, 5, "Orihalcum Ore", "- Craft Item")
ITEM(TITANIUM_BODY, 15, "Titanium Chestplate", "- Health Armor +1300")
ITEM(TITANIUM_FEET, 16, "Titanium Boots", "- Health Armor +1200")
ITEM(TITANIUMORE, 5, "Titanium Ore", "- Craft Item")
ITEM(ASTRALIUM_BODY, 15, "Astralium Chestplate", "- Health Armor +1600")
ITEM(ASTRALIUM_FEET, 16, "Astralium Boots", "- Health Armor +1500")
ITEM(ASTRALIUMORE, 5, "Astralium Ore", "- Craft Item")
ITEM(SLIMESOUL, 5, "Slime Soul", "- Craft Item")
ITEM(CRAFT_XP, 10, "CRAFT EXP", "- Achieve")
ITEM(FISHINGLEVEL, 0, "Fishing Exp", "- Fishing exp")
ITEM(COMMON_FISH, 4, "Common Fish", "- You got 10 exp")
ITEM(UNCOMMON_FISH, 4, "UnCommon Fish", "- You got 15 exp")
ITEM(RARE_FISH, 4, "Rare Fish", "- You got 20 exp")
ITEM(EPIC_FISH, 4, "Epic Fish", "- You got 30 exp")
ITEM(LEGENDARY_FISH, 4, "Legendary Fish", "- You got 45 exp")
ITEM(PET_ICE_FISH, 18, "Ice Fish Pet", "Pet...")
ITEM(PET_PIGGY, 18, "Piggy Pet", "Pet...")
ITEM(PET_FROG, 18, "Frog Pet", "Pet...")
ITEM(PET_BOMB, 18, "Bomb Pet", "Pet...")
ITEM(PET_DOLPHIN, 18, "Dolphin Pet", "Pet...")
ITEM(PET_IGOR, 18, "Igor Pet", "Pet...")
ITEM(PET_TIGER, 18, "Tiger Pet", "Pet...")
ITEM(PET_MONKEY, 18, "Monkey Pet", "Pet...")
ITEM(PET_MITHRIL_GOLEM, 18, "Mithril Golem Pet", "Pet...")
ITEM(PET_CLEVER, 18, "Cleaver Pet", "Pet...")
ITEM(ICE_FISH, 4, "Ice Fish", "- You got 35 exp")
ITEM(PREMIUM_BOX, 4, "Premium Packet", "- Thx for premium :D")
ITEM(PREMIUM_GOVNO, 12, "Premium Title", "- Thx for premium :D")
ITEM(PIXI_DUST, 5, "Pixi Dust", "- Craft Item")
ITEM(PEX_WINGS, 19, "Pex Wings", "- Wings")
ITEM(STORM_LASER, 1, "Storm Laser", "- Weapon / Upgrading")
ITEM(TARGET_AIM_GRENADE, 1, "Target Grenade", "- Weapon / Upgrading")
ITEM(ACCESSORY_ADD_SPEED, 2, "Add Speed Accssory", "- Accessory")
ITEM(ACCESSORY_ADD_DMG, 2, "Add Damage Accssory", "- Accessory")
ITEM(ACCESSORY_ADD_STEAL_HP, 2, "Add Steal HP Accssory", "- Accessory")
ITEM(ACCESSORY_ADD_HP, 2, "Add HP Accssory", "- Accessory")
ITEM(ACCESSORY_ADD_ARMOR, 2, "Add Armor Accssory", "- Accessory")
ITEM(ACCESSORY_ADD_MONEY, 2, "Add Money Accssory", "- Accessory")
